FROM osixia/openldap:1.5.0

# Copy your custom LDIF files into the image
COPY ../ldap-init /container/service/slapd/assets/config/bootstrap/ldif/custom/

# You can add any other setup or permission commands here
